import { getLanguage, Language } from './core';

const en = {
  title: 'Telegram backup', description: 'Back up completed recordings to your own private bot, directly from this device. No shared bot or server. Local files stay on your phone.',
  disconnected: 'No bot connected', awaiting: 'Waiting for your private chat', disabled: 'Connected · Backup is off', ready: 'Recording backup is on', uploading: 'Uploading to Telegram', required: 'Backup needs attention', checking: 'Checking backup status…', unavailable: 'Backup status is unavailable',
  connect: 'Connect my bot', connecting: 'Checking your bot…', verify: 'I pressed Start · Verify connection', verifying: 'Verifying your private chat…', enable: 'Enable backup', enabling: 'Enabling backup…', pausing: 'Pausing backup…', retrying: 'Preparing another attempt…', disconnecting: 'Disconnecting…',
  setupTitle: 'Connect a personal bot', setupBody: '1. Open the official BotFather and create a new private bot with /newbot.\n2. Paste the bot token here and connect. Use a new bot that is not used by another app.\n3. Open the link provided by this app, press Start in Telegram, then return and verify.',
  botFather: 'Open BotFather', tokenLabel: 'Your bot token', tokenPlaceholder: 'Paste the token from BotFather', tokenNote: 'Treat the token as a password. It is stored privately by Android after connection and is never shown in backup status. Do not share it.',
  start: 'Open my bot and press Start', pendingNote: 'Use this exact link to bind your private chat. Return here after pressing Start. If the link expires, reconnect.', bot: 'Connected bot',
  enableTitle: 'Back up all recordings?', enableBody: 'Upload all completed existing recordings and future completed recordings to your private Telegram chat. Large WAV files are split into playable, lossless parts. Your original local files are preserved.', enableConfirm: 'Enable and upload', cancel: 'Cancel',
  disconnect: 'Disconnect bot', disconnectTitle: 'Disconnect Telegram backup?', disconnectBody: 'Stop future uploads and remove the saved bot connection from this app. Local files and files already sent to Telegram remain.', disconnectConfirm: 'Disconnect',
  retry: 'Retry pending recordings', unknownTitle: 'Some uploads have no confirmed receipt', unknownBody: 'Telegram may already have received these parts, but this app could not confirm the response. Retrying them may send duplicates. Known successful parts will not be sent again.', unknownConfirm: 'Retry · Duplicates are possible', unknownNote: 'Unconfirmed uploads will not be retried automatically. An explicit retry may create duplicate parts in Telegram.',
  queued: 'Pending', uploaded: 'Uploaded', failed: 'Failed', unknown: 'Unconfirmed', countersNote: 'Counts refer to recordings. “Uploaded” means every part has a confirmed Telegram receipt.', refresh: 'Refresh status', recordingNote: 'Finish the recording before changing the bot connection or enabling backup.', switchLabel: 'Back up completed recordings to Telegram', errorLabel: 'Backup message', linkFailed: 'The Telegram link could not be opened. Check that a browser or Telegram is available.', generic: 'Telegram could not complete this action. Refresh the status and try again.',
  TOKEN_INVALID: 'The bot token is invalid. Copy the token for your own bot from BotFather.', BOT_IN_USE: 'This bot is already in use. Create a new personal bot for this app.', PRIVATE_CHAT_REQUIRED: 'Use a private chat with your bot, not a group or channel.', CONNECTION_EXPIRED: 'The connection link expired. Connect again to create a new link.', CONNECTION_NOT_CONFIRMED: 'Open the provided bot link, press Start, return here, and verify.', CHAT_AMBIGUOUS: 'The app could not identify one private chat. Reconnect using a fresh personal bot.', NOT_CONNECTED: 'Connect and verify your private bot first.', FOREGROUND_REQUIRED: 'Return to the app before changing the backup connection.', RECORDING_BUSY: 'Finish the recording before making this change.', CONNECTION_BUSY: 'Another connection action is in progress.', NETWORK: 'Telegram could not be reached. Pending files are preserved for retry.', RATE_LIMIT: 'Telegram requested a delay. The app will respect the retry interval.', RETRY_LIMIT: 'Automatic retry attempts are exhausted. Review the status before retrying.', CHAT_UNAVAILABLE: 'The private bot chat is unavailable. Check the bot and reconnect if needed.', UPLOAD_REJECTED: 'Telegram rejected an upload. The original local file is preserved.', UNKNOWN_OUTCOME: 'An upload response was not confirmed. Telegram may have received the file part.', UNKNOWN_OUTCOME_REQUIRES_CONFIRMATION: 'A retry needs your confirmation because it may create duplicate parts.', LOCAL_FILE_MISSING: 'A local recording is no longer available. It will not be recreated.', LOCAL_FILE_CHANGED: 'A local file changed. The app will not upload different bytes as the same recording.', UNSUPPORTED_WAV: 'This file cannot be backed up as supported WAV parts.', LOCAL_QUEUE_UNAVAILABLE: 'The local backup journal needs attention. Uploads are stopped to protect existing receipts.', LOCAL_QUEUE_FULL: 'The backup queue is full. Existing recordings and receipts are preserved.', RESPONSE_INVALID: 'Telegram returned an unexpected response. No successful receipt was assumed.', CANCELED: 'The action was canceled.', TELEGRAM_MODULE_UNAVAILABLE: 'This Android build does not include Telegram backup.', TELEGRAM_ANDROID_ONLY: 'Telegram backup is available in the Android app.', TELEGRAM_STATUS_INVALID: 'The app could not read a valid Telegram backup status.',
};

export type TelegramTextKey = keyof typeof en;
const he: Record<TelegramTextKey, string> = {
  title: 'גיבוי ל־Telegram', description: 'מגבים הקלטות שהסתיימו לבוט הפרטי שלכם, ישירות מהמכשיר. אין בוט משותף או שרת. הקבצים המקומיים נשארים בטלפון.',
  disconnected: 'אין בוט מחובר', awaiting: 'ממתין לחיבור הצ׳אט הפרטי', disabled: 'מחובר · הגיבוי כבוי', ready: 'גיבוי ההקלטות פעיל', uploading: 'מעלה ל־Telegram', required: 'הגיבוי דורש בדיקה', checking: 'בודק את מצב הגיבוי…', unavailable: 'מצב הגיבוי אינו זמין',
  connect: 'חיבור הבוט שלי', connecting: 'בודק את הבוט…', verify: 'לחצתי Start · אימות החיבור', verifying: 'מאמת את הצ׳אט הפרטי…', enable: 'הפעלת גיבוי', enabling: 'מפעיל גיבוי…', pausing: 'משהה גיבוי…', retrying: 'מכין ניסיון נוסף…', disconnecting: 'מנתק…',
  setupTitle: 'מחברים בוט אישי', setupBody: '1. פתחו את BotFather הרשמי וצרו בוט פרטי חדש באמצעות ‎/newbot.\n2. הדביקו כאן את הטוקן והתחברו. השתמשו בבוט חדש שאינו מחובר לאפליקציה אחרת.\n3. פתחו את הקישור שהאפליקציה מספקת, לחצו Start ב־Telegram, חזרו לכאן ואמתו.',
  botFather: 'פתיחת BotFather', tokenLabel: 'הטוקן של הבוט שלכם', tokenPlaceholder: 'הדביקו את הטוקן מ־BotFather', tokenNote: 'הטוקן הוא כמו סיסמה. לאחר החיבור Android שומר אותו באופן פרטי, והוא אינו מופיע במצב הגיבוי. אל תשתפו אותו.',
  start: 'פתיחת הבוט ולחיצה על Start', pendingNote: 'השתמשו בקישור הזה כדי לחבר את הצ׳אט הפרטי שלכם. חזרו לכאן אחרי לחיצה על Start. אם הקישור פג, התחברו מחדש.', bot: 'הבוט המחובר',
  enableTitle: 'לגבות את כל ההקלטות?', enableBody: 'כל ההקלטות הקיימות שהסתיימו וההקלטות העתידיות שיסתיימו יועלו לצ׳אט Telegram הפרטי שלכם. קובצי WAV גדולים מפוצלים לחלקים שניתן להשמיע, ללא אובדן מידע. הקובץ המקומי המקורי נשמר.', enableConfirm: 'הפעלה והעלאה', cancel: 'ביטול',
  disconnect: 'ניתוק הבוט', disconnectTitle: 'לנתק את הגיבוי ל־Telegram?', disconnectBody: 'העלאות עתידיות יופסקו ופרטי החיבור השמורים יוסרו מהאפליקציה. קבצים מקומיים וקבצים שכבר נשלחו ל־Telegram נשארים.', disconnectConfirm: 'ניתוק',
  retry: 'ניסיון נוסף להקלטות ממתינות', unknownTitle: 'לחלק מההעלאות אין אישור קבלה', unknownBody: 'ייתכן ש־Telegram כבר קיבל את החלקים, אבל האפליקציה לא הצליחה לאמת את התשובה. ניסיון נוסף עלול לשלוח עותקים כפולים. חלקים עם אישור הצלחה לא יישלחו שוב.', unknownConfirm: 'ניסיון נוסף · ייתכנו כפילויות', unknownNote: 'העלאות ללא אישור לא ינוסו שוב אוטומטית. ניסיון נוסף באישורכם עלול ליצור חלקים כפולים ב־Telegram.',
  queued: 'ממתינות', uploaded: 'הועלו', failed: 'נכשלו', unknown: 'ללא אישור', countersNote: 'המונים מתייחסים להקלטות. ״הועלו״ פירושו שלכל החלקים יש אישור קבלה מ־Telegram.', refresh: 'רענון מצב', recordingNote: 'סיימו את ההקלטה לפני שינוי חיבור הבוט או הפעלת הגיבוי.', switchLabel: 'גיבוי הקלטות שהסתיימו ל־Telegram', errorLabel: 'הודעת גיבוי', linkFailed: 'לא ניתן לפתוח את הקישור ל־Telegram. בדקו שיש דפדפן או אפליקציית Telegram זמינים.', generic: 'Telegram לא הצליח להשלים את הפעולה. רעננו את המצב ונסו שוב.',
  TOKEN_INVALID: 'הטוקן אינו תקין. העתיקו מ־BotFather את הטוקן של הבוט שלכם.', BOT_IN_USE: 'הבוט כבר נמצא בשימוש. צרו בוט אישי חדש לאפליקציה הזאת.', PRIVATE_CHAT_REQUIRED: 'השתמשו בצ׳אט פרטי עם הבוט, ולא בקבוצה או בערוץ.', CONNECTION_EXPIRED: 'קישור החיבור פג. התחברו שוב כדי ליצור קישור חדש.', CONNECTION_NOT_CONFIRMED: 'פתחו את קישור הבוט, לחצו Start, חזרו לכאן ואמתו.', CHAT_AMBIGUOUS: 'לא ניתן לזהות צ׳אט פרטי יחיד. התחברו מחדש באמצעות בוט אישי חדש.', NOT_CONNECTED: 'חברו ואמתו קודם את הבוט הפרטי.', FOREGROUND_REQUIRED: 'חזרו לאפליקציה לפני שינוי חיבור הגיבוי.', RECORDING_BUSY: 'סיימו את ההקלטה לפני השינוי.', CONNECTION_BUSY: 'פעולת חיבור אחרת עדיין מתבצעת.', NETWORK: 'לא ניתן להגיע ל־Telegram. קבצים ממתינים נשמרים לניסיון נוסף.', RATE_LIMIT: 'Telegram ביקש להמתין. האפליקציה תכבד את זמן ההמתנה.', RETRY_LIMIT: 'ניסיונות ההעלאה האוטומטיים הסתיימו. בדקו את המצב לפני ניסיון נוסף.', CHAT_UNAVAILABLE: 'הצ׳אט הפרטי עם הבוט אינו זמין. בדקו את הבוט והתחברו מחדש אם צריך.', UPLOAD_REJECTED: 'Telegram דחה העלאה. הקובץ המקומי המקורי נשמר.', UNKNOWN_OUTCOME: 'תשובת ההעלאה לא אומתה. ייתכן ש־Telegram קיבל את חלק הקובץ.', UNKNOWN_OUTCOME_REQUIRES_CONFIRMATION: 'נדרש אישורכם לניסיון נוסף שעלול ליצור חלקים כפולים.', LOCAL_FILE_MISSING: 'הקלטה מקומית כבר אינה זמינה. היא לא תיווצר מחדש.', LOCAL_FILE_CHANGED: 'קובץ מקומי השתנה. האפליקציה לא תעלה תוכן אחר כאותה הקלטה.', UNSUPPORTED_WAV: 'לא ניתן לגבות את הקובץ כחלקי WAV נתמכים.', LOCAL_QUEUE_UNAVAILABLE: 'יומן הגיבוי המקומי דורש בדיקה. ההעלאות נעצרו כדי לשמור על אישורי הקבלה הקיימים.', LOCAL_QUEUE_FULL: 'תור הגיבוי מלא. ההקלטות ואישורי הקבלה הקיימים נשמרים.', RESPONSE_INVALID: 'Telegram החזיר תשובה לא צפויה. לא הונח שההעלאה הצליחה.', CANCELED: 'הפעולה בוטלה.', TELEGRAM_MODULE_UNAVAILABLE: 'גרסת Android הזאת אינה כוללת גיבוי ל־Telegram.', TELEGRAM_ANDROID_ONLY: 'גיבוי ל־Telegram זמין באפליקציית Android.', TELEGRAM_STATUS_INVALID: 'לא ניתן לקרוא מצב גיבוי תקין של Telegram.',
};

const messages: Record<Language, Record<TelegramTextKey, string>> = {he, en};
export function telegramText(key: TelegramTextKey, language = getLanguage()): string { return messages[language][key]; }
